### PR TITLE
add pool temperature sensor

### PR DESCRIPTION
**Pull request by LeoThorsell**

### CODE REVIEW

**Comment by klejejs** [comment]
@LeoThorsell Hey! Thank you for the PR. Unfortunately, your solution will not work without changes to the underlying API as it does not provide this value ([see here](https://github.com/klejejs/python-thermia-online-api/blob/main/ThermiaOnlineAPI/model/HeatPump.py)).
You can try opening a PR for the API as well, I'd appreciate that, if not, I can look into it at some later date.

**Comment by LeoThorsell** [comment]
Hmm... what about this [line](https://github.com/klejejs/python-thermia-online-api/blob/ffe367cb36d377ff539a2d5cf40e20b9fa254807/ThermiaOnlineAPI/model/HeatPump.py#L550)

**Comment by dubtir** [comment]
Hei! Thanks a lot for having made this integration! Sorry if I'm posting this question the wrong place, but is it possible to control the pool heating currently with your integration? My pump uses Genesis. Thanks!

**Comment by klejejs** [comment]
@LeoThorsell you are correct. My heat pump does not have that value, that is why I did not realize it was there. This PR looks good, thanks for opening it.

**Comment by klejejs** [comment]
@dubtir I, unfortunately, cannot immediately tell what might be wrong as I have a different heat pump. I suggest you open a new issue and we can continue the discussion there.

**Pull request merged**
