### PR TITLE
Added heating operational time

### PR DESCRIPTION
**Pull request by mdr78**
Hi Krisjanis,

I am a bit unsure on the easiest way to test this with HA.

I have a working HA installation in a VM.
Any clues are appreciated, before I go cloning and hacking the VM.

Ray K

### CODE REVIEW

**Comment by klejejs** [comment]
Hi, @mdr78! Sorry for the delayed response.
This PR looks OK to me and there is nothing that seems wrong. Did [this PR](https://github.com/klejejs/python-thermia-online-api/pull/23) work as expected for you? I tried with my heat pump and unfortunately, I got nothing because my heat pump does not support that value, but if the `example.py` shows the expected value there, I think this is OK to merge.

**Comment by mdr78** [comment]
Hi @klejejs,

Before answering yes this works,  I have been trying to test myself on my own HomeAssistant setup and having a frustrating time of it.  I am using the [KVM/Proxmox HomeAssistant image](https://www.home-assistant.io/installation/alternative), which may be the source of the problem. 

To test, I have my own version of [ha-thermia-heat-pump-integration](https://github.com/mdr78/ha-thermia-heat-pump-integration), whose manifest.json and requirements.txt point to my own version of [python-thermia-online-api](https://github.com/mdr78/python-thermia-online-api). 

I am using the manual installation method documented in the [README](https://github.com/klejejs/ha-thermia-heat-pump-integration/blob/main/README.md).

The problem is that no matter what I try HomeAssistant will not install my github version of python-thermia-online-api, when I reinstall ha-thermia-heat-pump-integration. I have confirmed this by checking through the docker console.

    ➜  ~ docker exec -it homeassistant sh
    /config # grep REG_OPER_TIME_HOT_WATER /usr/local/lib/python3.12/site-packages/ThermiaOnlineAPI/const.py REG_OPER_TIME_HOT_WATER = "REG_OPER_TIME_HOT_WATER"
    /config # grep REG_OPER_TIME_HEATING /usr/local/lib/python3.12/site-packages/ThermiaOnlineAPI/const.py 
    /config # 

Any ideas how I can force home assistant to redownload and reinstall the dependencies of ha-thermia-heat-pump-integration.

**Comment by mdr78** [comment]
(BTW sorry for the long hiatus between responses.)

**Comment by mdr78** [comment]
I can confirm that I have tested and it works perfectly. 
It needed one small update.

Screenshot 2024-09-03 10 45 25 AM

**Comment by klejejs** [comment]
Looks good! 👍🏻

**Pull request merged**
